#!/usr/bin/python3
from sys import argv

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        num = file.readline()

        while num != '\n':
            num = int(num.split('\n')[0])

            i = 2
            while num % i:
                i+=1
            print("{}={}*{}".format(num, num//i, i))
            num = file.readline()
except:
    pass
