#!/usr/bin/python3
from sys import argv

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        num = file.readline()

        while num != '':
            num = int(num)

            i = 2
            while num % i:
                i+=1
            print("{}={}*{}".format(num, i, num//i))
            num = file.readline()
except:
    pass
